export const REGEX = {
    COMMENT: /\/\* Analyze the following code in .*? and complete the code based on the context. .*? Remove this commented instruction in complete code. \*\//g,
    COMMENTED: /\/\/.*$|\/\*[\s\S]*?\*\//gm,
    BLOCK_START: /{\s*$/,
    BLOCK_END: /^\s*}\s*$/,
    EMPTY_LINE: /^\s*$/,
    TRIPLE_QUOTES_CONTENT: /```([\s\S]*?)```/,
    KEYWORDS: /\b(namespace|import|contract|transaction|public field|from|extends|asset|concept|template)\b/g,
    GENERATOR_COMMENT: "// This code is generated by Accord Copilot Model Generator"
};

export const DEFAULTS = {
    MAX_RETRIES: 2,
    TEMP_DOCUMENT_EXTENSION: 'temp-document.',
    MAX_CACHE_ITEMS: 100 
};