export const REGEX = {
    COMMENT: /\/\* Analyze the following code in .*? and complete the code based on the context. .*? Remove this commented instruction in complete code. \*\//g,
    COMMENTED: /\/\/.*$|\/\*[\s\S]*?\*\//gm,
    BLOCK_START: /{\s*$/,
    BLOCK_END: /^\s*}\s*$/,
    EMPTY_LINE: /^\s*$/,
    TRIPLE_QUOTES_CONTENT: /```([\s\S]*?)```/,
    KEYWORDS: /\b(namespace|import|contract|transaction|public field|from|extends|asset|concept|template)\b/g,
    GENERATOR_COMMENT: "// This code is generated by Accord Copilot Model Generator"
};

export const PROVIDERS = {
    GEMINI: 'gemini',
    OPENAI: 'openai',
    ANTHROPIC: 'anthropic',
    HUGGINGFACE: 'huggingface',
};

export const DEFAULTS = {
    MAX_RETRIES: 2,
    TEMP_DOCUMENT_EXTENSION: 'temp-document.',
    MAX_CACHE_ITEMS: 100 
};

export const LLM_ENDPOINTS = {
    GEMINI: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent',
    OPENAI: 'https://api.openai.com/v1/chat/completions',
    ANTHROPIC: 'https://api.anthropic.com/v1/complete',
    HUGGINGFACE: 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1/v1/chat/completions'
};

export const LLM_EMDEDDINGS_ENDPOINTS = {
    GEMINI: 'https://generativelanguage.googleapis.com/v1beta/models/embedding-001:embedContent',
    OPENAI: 'https://api.openai.com/v1/embeddings'
};