name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Tests

    strategy:
      matrix:
        node-version:
          - 20.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run package:vsix
      - run: npm install -g vsce

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test --silent
        shell: bash

      - name: Test (macOS / Windows)
        if: runner.os != 'Linux'
        run: npm test --silent
        shell: bash
