name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Tests

    strategy:
      matrix:
        node-version:
          - 20.x
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - run: npm ci
      - run: npm run package:vsix
      - run: npm install -g vsce
    
      - name: Test
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run -a npm test --silent
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm test
          else
            npm test --silent
          fi
        shell: bash
